package application.controller;

import application.bills.Bill;
import application.repository.BillDAORepository;
import application.repository.BillRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@CrossOrigin
@RestController
public class BillController {

    @Autowired
    private BillRepository billRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BillDAORepository billDAORepository;

    @RequestMapping("/bills")
    public List<Bill> getBills() {
        return (List<Bill>) billDAORepository.findAll();
//        return billRepository.getBills();
    }

    @PostMapping("/bill")
    public @ResponseBody List<Bill> newBill(@RequestBody Bill newBill) {
        newBill.setStatus("Unpaid");
        billDAORepository.save(newBill);
        return (List<Bill>) billDAORepository.findAll();
    }

    @DeleteMapping("/bill")
    public List<Bill> deleteBill(@RequestParam("ids") String ids) {
        billRepository.deleteBill(ids);
        return billRepository.getBills();
    }
}