package application;

import application.bills.Bill;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.ResourceAccessException;

import java.util.List;
import java.util.Optional;

@CrossOrigin
@RestController
@SuppressWarnings("unused")
public class BillController {

    @SuppressWarnings("unused")
    @Autowired
    private BillRepository billRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BillDAORepository billDAORepository;

    @RequestMapping("/bills")
    public List<Bill> getBills() {
        return billDAORepository.findAll(new Sort(Sort.Direction.ASC, "dueDate"));
    }

    @PostMapping("/bill")
    public @ResponseBody List<Bill> newBill(@RequestBody Bill newBill) {
        newBill.setStatus("Unpaid");
        billDAORepository.save(newBill);
        return (List<Bill>) billDAORepository.findAll();
    }

    @PutMapping("/bill/{id}")
    public @ResponseBody List<Bill> payBill(@PathVariable(value="id") Integer billId) {
        Bill bill = billDAORepository.findById(billId)
                .orElseThrow(() -> new ResourceAccessException("Bill not found"));
        bill.setStatus("Paid");
        billDAORepository.save(bill);
        return (List<Bill>) billDAORepository.findAll();
    }

    @DeleteMapping("/bill")
    public List<Bill> deleteBill(@RequestParam("ids") String ids) {
        billRepository.deleteBill(ids);
        return billRepository.getBills();
    }
}